"""cria usuarios, simulados e questoes

Revision ID: d1518881a28e
Revises: 
Create Date: 2026-09-24 18:13:25.725363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1518881a28e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_questao', sa.Integer(), nullable=False),
    sa.Column('componente_curricular', sa.Enum('PORTUGUES', 'MATEMATICA', 'CIENCIAS', 'HISTORIA', 'GEOGRAFIA', 'LITERATURA', 'GRAMATICA', 'FILOSOFIA', 'SOCIOLOGIA', 'ARTES', 'INGLES', 'ESPANHOL', 'LINGUA_EXTRANJERA', 'QUIMICA', 'BIOLOGIA', 'FISICA', 'EDUCACAO_FISICA', 'ENSINO_RELIGIOSO', 'ATUALIDADES', name='disciplina'), nullable=False),
    sa.Column('alternativa_correta', sa.Enum('A', 'B', 'C', 'D', 'E', name='alternativacorreta'), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('simulado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulado_id'], ['simulados.id'], name='fk_questoes_simulado'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questoes_id'), ['id'], unique=False)

    with op.batch_alter_table('simulados', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_simulados_usuario', 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulados', schema=None) as batch_op:
        batch_op.drop_constraint('fk_simulados_usuario', type_='foreignkey')
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questoes_id'))

    op.drop_table('questoes')
    # ### end Alembic commands ###
